var blue_coin_hints = {
  // Delfino Plaza
  dp_bc1: "",
  dp_bc2: "",
  dp_bc3: "",
  dp_bc4: "",
  dp_bc5: "",
  dp_bc6: "",
  dp_bc7: "",
  dp_bc8: "",
  dp_bc9: "",
  dp_bc10: "",
  dp_bc11: "",
  dp_bc12: "",
  dp_bc13: "",
  dp_bc14: "",
  dp_bc15: "",
  dp_bc16: "",
  dp_bc17: "",
  dp_bc18: "",
  dp_bc19: "",
  // Delfino Airstrip
  da_bc1: "",
  // Corona Mountain
  cm_bc1: "",
  cm_bc2: "",
  cm_bc3: "",
  cm_bc4: "",
  cm_bc5: "",
  cm_bc6: "",
  cm_bc7: "",
  cm_bc8: "",
  cm_bc9: "",
  cm_bc10: "",
  // Bianco Hills
  bh_bc1: "(Episode 1) Swim up the stream, and you will find the coin near the gate at the end.",
  bh_bc2: "(Episode 1) Clean the M Graffiti off the back wall of the building in the north part of the village.",
  bh_bc3: "(Episode 1) On the path that leads from the stream along the wall, clean the M Graffiti off the wall near the wheel.",
  bh_bc4: "(Episode 1) In the house by the stream with the balcony, jump up to the adjoining building, hover to the balcony, and spray the left alcove.",
  bh_bc5: "(Episode 1) Hover to this mid-air Blue Coin from the windmill-roofed building in the southwest corner of the village.",
  bh_bc6: "(Episode 1) Spin jump and hover to the roof of the building north of the previous Blue Coin, and find the Blue Coin in the right spire.",
  bh_bc7: "(Episode 1) M Graffiti on top of the millstone wall (just south of the wheel).",
  bh_bc8: "(Episode 1) X Graffiti on the wall. Spray it from where you got Blue Coin #7, then fall to the right to get the Blue Coin. Use the Wall Kicks to return to the top of the wall.",
  bh_bc9: "(Episode 1) The X Graffiti corresponding to Blue Coin #8. Shoot the X from above, then fall to the left to grab the Blue Coin.",
  bh_bc10: "(Episode 1) From the wall, shoot the first mini-windmill on the east side of the wall with water until a Blue Coin appears on its platform.",
  bh_bc11: "(Episode 1) At the bottom of the lake, near the ledges on the west.",
  bh_bc12: "(Episode 1) On the rocky spire south of the windmill in the lake, spray the center with water to make the Blue Coin appear.",
  bh_bc13: "(Episode 1) Clean off the M Graffiti near the top of the Big Windmill.",
  bh_bc14: "(Episode 3) 	From the wall, jump onto the impossible-to-climb banana trees. At one farthest east, by the rope bridge, hover-spray the center of the treetop, and a Blue Coin will appear.",
  bh_bc15: "(Episode 3) In the village, there is a Blue Coin on a small cliff. Climb on top of the tallest building in the village and hover over to it.",
  bh_bc16: "(Episode 3) Use the moving ledges on the arms of the big windmill. Once you are near the top, you there is a Blue Coin on the mini-windmill in front of the large windmill.",
  bh_bc17: "(Episode 3) Destroy the Pokey on top of the Big Windmill, where Petey Piranha used to be.",
  bh_bc18: "(Episode 4) Destroy the Pokey on the rock steps along the cliff at the edge of the stream in the southeastern part of this area.",
  bh_bc19: "(Episode 4) Jump up to the hills where the Episode 3 cave is to find a man covered in mud. Clean him off for a Blue Coin.",
  bh_bc20: "(Episode 4) You can get a Blue Coin under the screen bridge in the second part of the level by jumping onto it from a rope under the bridge.",
  bh_bc21: "(Episode 5) Go to the tower at the south end of the wall. Clean off the Pianta for a Blue Coin.",
  bh_bc22: "(Episode 5) In the ledge area where you fought Petey Piranha again, rocket onto the five platforms. A Blue Coin is in the middle.",
  bh_bc23: "(Episode 6) There is a blue bird on the rope in the village (the high up rope that you use to get the shine sprite in Episode 4).",
  bh_bc24: "(Episode 6) In the village, climb up on top of the left spire of the largest building. From here, look towards the area where you wake up Petey Piranha in Episode 5. You will see a blue coin in mid air; hover to reach it.",
  bh_bc25: "(Episode 6) Inflate the white clouds with water and jump across to where Petey Piranha was sleeping in Episode 5. Spray the top of the pillar for a Blue Coin.",
  bh_bc26: "(Episode 7) Another Blue Coin appears at the bottom of the lake.",
  bh_bc27: "(Episode 7) A pair of Os appear in buildings in the village. One is at the east edge, and one in the middle. Spray one and dive-run to the other.",
  bh_bc28: "(Episode 7) O Graffiti counterpart.",
  bh_bc29: "(Episode 8) Eat the group of blue butterflies in the village as Yoshi.",
  bh_bc30: "(Episode 8) Eat all the bees in the one of the beehives as Yoshi after you spray it off the tree.",
};