var blue_coin_hints = {
  // Delfino Plaza
  dp_bc1: "From the southeast part of the beach, swim around to the back of the building with bars on the windows. Jump and hover through the entrance in the back.",
  dp_bc2: "",
  dp_bc3: "",
  dp_bc4: "",
  dp_bc5: "If you take the main manhole network up to the grassy areas north of the Shine Gate, you will see a large M Graffiti on the north side of the northwest tower (the one with the weathervane on top).",
  dp_bc6: "Hover around to the tower south of the northeast tower with the weathervane, or take the east manhole tunnel and come out of the nearby roof. You will see a large crate on the south side of the tower. Ground Pound it to reveal an M Graffiti",
  dp_bc7: "Smash the create along the canal, just south of the Shine Gate, to reveal an M Graffiti",
  dp_bc8: "",
  dp_bc9: "",
  dp_bc10: "",
  dp_bc11: "",
  dp_bc12: "",
  dp_bc13: "",
  dp_bc14: "",
  dp_bc15: "",
  dp_bc16: "",
  dp_bc17: "",
  dp_bc18: "",
  dp_bc19: "",
  // Delfino Airstrip
  da_bc1: "",
  // Corona Mountain
  cm_bc1: "",
  cm_bc2: "",
  cm_bc3: "",
  cm_bc4: "",
  cm_bc5: "",
  cm_bc6: "",
  cm_bc7: "",
  cm_bc8: "",
  cm_bc9: "",
  cm_bc10: "",
  // Bianco Hills
  bh_bc1: "(Episode 1) Swim up the stream, and you will find the coin near the gate at the end.",
  bh_bc2: "(Episode 1) Clean the M Graffiti off the back wall of the building in the north part of the village.",
  bh_bc3: "(Episode 1) On the path that leads from the stream along the wall, clean the M Graffiti off the wall near the wheel.",
  bh_bc4: "(Episode 1) In the house by the stream with the balcony, jump up to the adjoining building, hover to the balcony, and spray the left alcove.",
  bh_bc5: "(Episode 1) Hover to this mid-air Blue Coin from the windmill-roofed building in the southwest corner of the village.",
  bh_bc6: "(Episode 1) Spin jump and hover to the roof of the building north of the previous Blue Coin, and find the Blue Coin in the right spire.",
  bh_bc7: "(Episode 1) M Graffiti on top of the millstone wall (just south of the wheel).",
  bh_bc8: "(Episode 1) X Graffiti on the wall. Spray it from where you got Blue Coin #7, then fall to the right to get the Blue Coin. Use the Wall Kicks to return to the top of the wall.",
  bh_bc9: "(Episode 1) The X Graffiti corresponding to Blue Coin #8. Shoot the X from above, then fall to the left to grab the Blue Coin.",
  bh_bc10: "(Episode 1) From the wall, shoot the first mini-windmill on the east side of the wall with water until a Blue Coin appears on its platform.",
  bh_bc11: "(Episode 1) At the bottom of the lake, near the ledges on the west.",
  bh_bc12: "(Episode 1) On the rocky spire south of the windmill in the lake, spray the center with water to make the Blue Coin appear.",
  bh_bc13: "(Episode 1) Clean off the M Graffiti near the top of the Big Windmill.",
  bh_bc14: "(Episode 3) 	From the wall, jump onto the impossible-to-climb banana trees. At one farthest east, by the rope bridge, hover-spray the center of the treetop, and a Blue Coin will appear.",
  bh_bc15: "(Episode 3) In the village, there is a Blue Coin on a small cliff. Climb on top of the tallest building in the village and hover over to it.",
  bh_bc16: "(Episode 3) Use the moving ledges on the arms of the big windmill. Once you are near the top, you there is a Blue Coin on the mini-windmill in front of the large windmill.",
  bh_bc17: "(Episode 3) Destroy the Pokey on top of the Big Windmill, where Petey Piranha used to be.",
  bh_bc18: "(Episode 4) Destroy the Pokey on the rock steps along the cliff at the edge of the stream in the southeastern part of this area.",
  bh_bc19: "(Episode 4) Jump up to the hills where the Episode 3 cave is to find a man covered in mud. Clean him off for a Blue Coin.",
  bh_bc20: "(Episode 4) You can get a Blue Coin under the screen bridge in the second part of the level by jumping onto it from a rope under the bridge.",
  bh_bc21: "(Episode 5) Go to the tower at the south end of the wall. Clean off the Pianta for a Blue Coin.",
  bh_bc22: "(Episode 5) In the ledge area where you fought Petey Piranha again, rocket onto the five platforms. A Blue Coin is in the middle.",
  bh_bc23: "(Episode 6) There is a blue bird on the rope in the village (the high up rope that you use to get the shine sprite in Episode 4).",
  bh_bc24: "(Episode 6) In the village, climb up on top of the left spire of the largest building. From here, look towards the area where you wake up Petey Piranha in Episode 5. You will see a blue coin in mid air; hover to reach it.",
  bh_bc25: "(Episode 6) Inflate the white clouds with water and jump across to where Petey Piranha was sleeping in Episode 5. Spray the top of the pillar for a Blue Coin.",
  bh_bc26: "(Episode 7) Another Blue Coin appears at the bottom of the lake.",
  bh_bc27: "(Episode 7) A pair of Os appear in buildings in the village. One is at the east edge, and one in the middle. Spray one and dive-run to the other.",
  bh_bc28: "(Episode 7) O Graffiti counterpart.",
  bh_bc29: "(Episode 8) Eat the group of blue butterflies in the village as Yoshi.",
  bh_bc30: "(Episode 8) Eat all the bees in the one of the beehives as Yoshi after you spray it off the tree.",
  // Ricco Harbour
  rh_bc1: "(Episode 1) Clean the M Graffiti on the side of the building near the starting point.",
  rh_bc2: "(Episode 1) Clean the M Graffiti above the building near the starting point.",
  rh_bc3: "(Episode 1) Clean the M Graffiti in the ship's hold hidden under the sludge.",
  rh_bc4: "(Episode 1) Clean the M Graffiti on the side of the ship.",
  rh_bc5: "(Episode 1) Clean the M Graffiti on the dock near the ship.",
  rh_bc6: "(Episode 1) Ground Pound open the crate in the same part of the docks where you got Blue Coin #5.",
  rh_bc7: "(Episode 1) Spray the wall in the same part of the docks where you got Blue Coins #5 and #6 until a Sun Shape appears.",
  rh_bc8: "(Episode 1) Located underwater beneath the peach-colored platform with the arrow on it.",
  rh_bc9: "(Episode 1) Atop the fountain in the upper part of town. Jump and hover onto the center and backflip up.",
  rh_bc10: "(Episode 1) Clean the M Graffiti on the side of the building in the upper part of town.",
  rh_bc11: "(Episode 1) Clean the M Graffiti in the balconies above the upper part of town, past the last manhole.",
  rh_bc12: "(Episode 1) On one of the catwalks around the tower. You can hover over from the green terrace edge near the upper manhole balcony, or rocket up later.",
  rh_bc13: "(Episode 1) Continuously spray the propeller above the yellow submarine to raise it out of the water and get a Blue Coin.",
  rh_bc14: "(Episode 1) On the second lattice level above the harbor.",
  rh_bc15: "(Episode 1) On the third lattice level above the harbor.",
  rh_bc16: "(Episode 1) On top of the crane. You can drop onto this from Blue Coin #14.",
  rh_bc17: "(Episode 2) Above the water. You can jump to it with the Blooper, or use the rocket later.",
  rh_bc18: "(Episode 2) Above the Water. You can jump to it with the Blooper, or use the rocket later.",
  rh_bc19: "(Episode 3) Destroy the Yellow Spider on the boat.",
  rh_bc20: "(Episode 3) Destroy the Yellow Spider on the boat.",
  rh_bc21: "(Episode 3) Clean the X Graffiti on the tower, then use your rocket to blast up to the higher part of town, and grab the Blue Coin from the other X.",
  rh_bc22: "(Episode 3) Use your rocket on top of the tower to get the highest Blue Coin. You will need to unleash the rocket at the height of a normal jump.",
  rh_bc23: "(Episode 3) Use your rocket at the edge of one of the support pillars in the water. Release the rocket at the height of your jump.",
  rh_bc24: "(Episode 3) Use your rocket on the network of pillars in the far part of the harbor. Atop one of the higher pillars, you will find an M Graffiti.",
  rh_bc25: "(Episode 3) Use your rocket to get to the cliffs with the palm trees in the far part of the harbor. The second cliff has an M Graffiti.",
  rh_bc26: "(Episode 4) Defeat the Blooper in the cage where you got the Episode 3 Shine.",
  rh_bc27: "(Episode 6) Spray the basket of fish in the fish market.",
  rh_bc28: "(Episode 7) Use the Turbo Nozzle to get Blue Coin #21's counterpart by spraying the X Graffiti and turboing to the tower.",
  rh_bc29: "(Episode 8) Use Yoshi to eat all the blue butterflies near the fish market.",
  rh_bc30: "(Episode 8) Use Yoshi to eat the Yellow Spider on the wall near the tower.",
  // Gelato Beach
  // Pinna Park
  pp_bc1: "(Episode 1) ",
  pp_bc2: "(Episode 1) ",
  pp_bc3: "(Episode 1) ",
  pp_bc4: "(Episode 1) ",
  pp_bc5: "(Episode 1) ",
  pp_bc6: "(Episode 1) ",
  pp_bc7: "(Episode 1) M Graffiti on top of the millstone wall (just south of the wheel).",
  pp_bc8: "(Episode 1) X Graffiti on the wall. Spray it from where you got Blue Coin #7, then fall to the right to get the Blue Coin. Use the Wall Kicks to return to the top of the wall.",
  pp_bc9: "(Episode 1) The X Graffiti corresponding to Blue Coin #8. Shoot the X from above, then fall to the left to grab the Blue Coin.",
  pp_bc10: "(Episode 1) From the wall, shoot the first mini-windmill on the east side of the wall with water until a Blue Coin appears on its platform.",
  pp_bc11: "(Episode 1) At the bottom of the lake, near the ledges on the west.",
  pp_bc12: "(Episode 1) On the rocky spire south of the windmill in the lake, spray the center with water to make the Blue Coin appear.",
  pp_bc13: "(Episode 1) Clean off the M Graffiti near the top of the Big Windmill.",
  pp_bc14: "(Episode 3) 	From the wall, jump onto the impossible-to-climb banana trees. At one farthest east, by the rope bridge, hover-spray the center of the treetop, and a Blue Coin will appear.",
  pp_bc15: "(Episode 3) In the village, there is a Blue Coin on a small cliff. Climb on top of the tallest building in the village and hover over to it.",
  pp_bc16: "(Episode 3) Use the moving ledges on the arms of the big windmill. Once you are near the top, you there is a Blue Coin on the mini-windmill in front of the large windmill.",
  pp_bc17: "(Episode 3) Destroy the Pokey on top of the Big Windmill, where Petey Piranha used to be.",
  pp_bc18: "(Episode 4) Destroy the Pokey on the rock steps along the cliff at the edge of the stream in the southeastern part of this area.",
  pp_bc19: "(Episode 4) Jump up to the hills where the Episode 3 cave is to find a man covered in mud. Clean him off for a Blue Coin.",
  pp_bc20: "(Episode 4) You can get a Blue Coin under the screen bridge in the second part of the level by jumping onto it from a rope under the bridge.",
  pp_bc21: "(Episode 5) Go to the tower at the south end of the wall. Clean off the Pianta for a Blue Coin.",
  pp_bc22: "(Episode 5) In the ledge area where you fought Petey Piranha again, rocket onto the five platforms. A Blue Coin is in the middle.",
  pp_bc23: "(Episode 6) There is a blue bird on the rope in the village (the high up rope that you use to get the shine sprite in Episode 4).",
  pp_bc24: "(Episode 6) In the village, climb up on top of the left spire of the largest building. From here, look towards the area where you wake up Petey Piranha in Episode 5. You will see a blue coin in mid air; hover to reach it.",
  pp_bc25: "(Episode 6) Inflate the white clouds with water and jump across to where Petey Piranha was sleeping in Episode 5. Spray the top of the pillar for a Blue Coin.",
  pp_bc26: "(Episode 7) Another Blue Coin appears at the bottom of the lake.",
  pp_bc27: "(Episode 7) A pair of Os appear in buildings in the village. One is at the east edge, and one in the middle. Spray one and dive-run to the other.",
  pp_bc28: "(Episode 7) O Graffiti counterpart.",
  pp_bc29: "(Episode 8) Eat the group of blue butterflies in the village as Yoshi.",
  pp_bc30: "(Episode ) .",
};