var blue_coin_hints = {
  // Delfino Plaza
  dp_bc1: "(Delfino Plaza) From the southeast part of the beach, swim around to the back of the building with bars on the windows. Jump and hover through the entrance in the back.",
  dp_bc2: "(Delfino Plaza) In a manhole tunnel on the main island, after a few turns.",
  dp_bc3: "(Delfino Plaza) In a manhole tunnel under the canal, just south of the Shine Gate.",
  dp_bc4: "(Delfino Plaza) In a manhole tunnel beneath the highest lake north of the Shine Gate.",
  dp_bc5: "(Delfino Plaza) You will see a large M Graffiti on the north side of the northwest tower (the one with the weathervane on top). Hover over to it and clean it off to get the coin.",
  dp_bc6: "(Delfino Plaza) Hover around to the tower south of the northeast tower with the weathervane, or take the east manhole tunnel and come out of the nearby roof. You will see a large crate on the south side of the tower. Ground Pound it to reveal an M Graffiti.",
  dp_bc7: "(Delfino Plaza) Smash the create along the canal, just south of the Shine Gate, to reveal an M Graffiti.",
  dp_bc8: "(Delfino Plaza) Blue bird perched just west of the building with the giant pineapple in its chimney; can easily be hit from near that pineapple.",
  dp_bc9: "(Delfino Plaza) Blue bird perched on a building just west of the Shine Gate.",
  dp_bc10: "(Delfino Plaza) After unlocking Bianco hills, the X graffiti on the Pianta statue.",
  dp_bc11: "(Delfino Plaza) After unlocking Bianco hills, the X graffiti in the southwest corner of town, at the end of the pier, behind the building with a Shine visible through the window.",
  dp_bc12: "(Delfino Plaza) The red Pianta beside the canal wants 3 bananas in her basket.",
  dp_bc13: "(Delfino Plaza) The orange Pianta to the right of the Shine Gate wants 3 pineapples in her basket.",
  dp_bc14: "(Delfino Plaza) The Pianta to the left of the Shine Gate wants 3 durians in her basket.",
  dp_bc15: "(Delfino Plaza) The Pianta on the small island west of the plaza wants 3 coconuts in her basket (they grow on the tree).",
  dp_bc16: "(Delfino Plaza) After unlocking Gelato Beach, you will see a Pianta with his back on fire running back and forth on the road along the east beach. After you douse the flames, talk to the Pianta.",
  dp_bc17: "(Delfino Plaza) After unlocking Yoshi, spray the orange goo on the backside of the Police Station tower.",
  dp_bc18: "(Delfino Plaza) After unlocking Yoshi, spray the orange goo on the high tower in the northwest part of town.",
  dp_bc19: "(Delfino Plaza) After unlocking the turbo nozzle, break through the base of the pillar in the ocean northeast of the plaza.",
  // Delfino Airstrip
  da_bc1: "(Delfino Airstrip) Melt the ice cube in the cabana.",
  // Corona Mountain
  cm_bc1: "(Corona Mountain) In plain sight past the first 1-up.",
  cm_bc2: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc3: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc4: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc5: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc6: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc7: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc8: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc9: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  cm_bc10: "(Corona Mountain) Steer the boat near the blue coins on the lava.",
  // Bianco Hills
  bh_bc1: "(Episode 1) Swim up the stream and you will find the coin near the gate at the end.",
  bh_bc2: "(Episode 1) Clean the M Graffiti off the back wall of the building in the north part of the village.",
  bh_bc3: "(Episode 1) On the path that leads from the stream along the wall, clean the M Graffiti off the wall near the wheel.",
  bh_bc4: "(Episode 1) In the house by the stream with the balcony, jump up to the adjoining building, hover to the balcony, and spray the left alcove.",
  bh_bc5: "(Episode 1) Hover to this mid-air Blue Coin from the windmill-roofed building in the southwest corner of the village.",
  bh_bc6: "(Episode 1) Spin jump and hover to the roof of the building north of the previous Blue Coin, and find the Blue Coin in the right spire.",
  bh_bc7: "(Episode 1) M Graffiti on top of the millstone wall (just south of the wheel).",
  bh_bc8: "(Episode 1) X Graffiti on the wall. Spray it from where you got Blue Coin #7, then fall to the right to get the Blue Coin. Use the Wall Kicks to return to the top of the wall.",
  bh_bc9: "(Episode 1) The X Graffiti corresponding to Blue Coin #8. Shoot the X from above, then fall to the left to grab the Blue Coin.",
  bh_bc10: "(Episode 1) From the wall, shoot the first mini-windmill on the east side of the wall with water until a Blue Coin appears on its platform.",
  bh_bc11: "(Episode 1) At the bottom of the lake, near the ledges on the west.",
  bh_bc12: "(Episode 1) On the rocky spire south of the windmill in the lake, spray the center with water to make the Blue Coin appear.",
  bh_bc13: "(Episode 1) Clean off the M Graffiti near the top of the Big Windmill.",
  bh_bc14: "(Episode 3) 	From the wall, jump onto the impossible-to-climb banana trees. At one farthest east, by the rope bridge, hover-spray the center of the treetop, and a Blue Coin will appear.",
  bh_bc15: "(Episode 3) In the village, there is a Blue Coin on a small cliff. Climb on top of the tallest building in the village and hover over to it.",
  bh_bc16: "(Episode 3) Use the moving ledges on the arms of the big windmill. Once you are near the top, you there is a Blue Coin on the mini-windmill in front of the large windmill.",
  bh_bc17: "(Episode 3) Destroy the Pokey on top of the Big Windmill, where Petey Piranha used to be.",
  bh_bc18: "(Episode 4) Destroy the Pokey on the rock steps along the cliff at the edge of the stream in the southeastern part of this area.",
  bh_bc19: "(Episode 4) Jump up to the hills where the Episode 3 cave is to find a man covered in mud. Clean him off for a Blue Coin.",
  bh_bc20: "(Episode 4) You can get a Blue Coin under the screen bridge in the second part of the level by jumping onto it from a rope under the bridge.",
  bh_bc21: "(Episode 5) Go to the tower at the south end of the wall. Clean off the Pianta for a Blue Coin.",
  bh_bc22: "(Episode 5) In the ledge area where you fought Petey Piranha again, rocket onto the five platforms. A Blue Coin is in the middle.",
  bh_bc23: "(Episode 6) There is a blue bird on the rope in the village (the high up rope that you use to get the shine sprite in Episode 4).",
  bh_bc24: "(Episode 6) In the village, climb up on top of the left spire of the largest building. From here, look towards the area where you wake up Petey Piranha in Episode 5. You will see a blue coin in mid air; hover to reach it.",
  bh_bc25: "(Episode 6) Inflate the white clouds with water and jump across to where Petey Piranha was sleeping in Episode 5. Spray the top of the pillar for a Blue Coin.",
  bh_bc26: "(Episode 7) Another Blue Coin appears at the bottom of the lake.",
  bh_bc27: "(Episode 7) A pair of Os appear in buildings in the village. One is at the east edge, and one in the middle. Spray one and dive-run to the other.",
  bh_bc28: "(Episode 7) O Graffiti counterpart.",
  bh_bc29: "(Episode 8) Eat the group of blue butterflies in the village as Yoshi.",
  bh_bc30: "(Episode 8) Eat all the bees in the one of the beehives as Yoshi after you spray it off the tree.",
  // Ricco Harbour
  rh_bc1: "(Episode 1) Clean the M Graffiti on the side of the building near the starting point.",
  rh_bc2: "(Episode 1) Clean the M Graffiti above the building near the starting point.",
  rh_bc3: "(Episode 1) Clean the M Graffiti in the ship's hold hidden under the sludge.",
  rh_bc4: "(Episode 1) Clean the M Graffiti on the side of the ship.",
  rh_bc5: "(Episode 1) Clean the M Graffiti on the dock near the ship.",
  rh_bc6: "(Episode 1) Ground Pound open the crate in the same part of the docks where you got Blue Coin #5.",
  rh_bc7: "(Episode 1) Spray the wall in the same part of the docks where you got Blue Coins #5 and #6 until a Sun Shape appears.",
  rh_bc8: "(Episode 1) Located underwater beneath the peach-colored platform with the arrow on it.",
  rh_bc9: "(Episode 1) Atop the fountain in the upper part of town. Jump and hover onto the center and backflip up.",
  rh_bc10: "(Episode 1) Clean the M Graffiti on the side of the building in the upper part of town.",
  rh_bc11: "(Episode 1) Clean the M Graffiti in the balconies above the upper part of town, past the last manhole.",
  rh_bc12: "(Episode 1) On one of the catwalks around the tower. You can hover over from the green terrace edge near the upper manhole balcony, or rocket up later.",
  rh_bc13: "(Episode 1) Continuously spray the propeller above the yellow submarine to raise it out of the water and get a Blue Coin.",
  rh_bc14: "(Episode 1) On the second lattice level above the harbor.",
  rh_bc15: "(Episode 1) On the third lattice level above the harbor.",
  rh_bc16: "(Episode 1) On top of the crane. You can drop onto this from Blue Coin #14.",
  rh_bc17: "(Episode 2) Above the water. You can jump to it with the Blooper, or use the rocket later.",
  rh_bc18: "(Episode 2) Above the Water. You can jump to it with the Blooper, or use the rocket later.",
  rh_bc19: "(Episode 3) Destroy the Yellow Spider on the boat.",
  rh_bc20: "(Episode 3) Destroy the Yellow Spider on the boat.",
  rh_bc21: "(Episode 3) Clean the X Graffiti on the tower, then use your rocket to blast up to the higher part of town, and grab the Blue Coin from the other X.",
  rh_bc22: "(Episode 3) Use your rocket on top of the tower to get the highest Blue Coin. You will need to unleash the rocket at the height of a normal jump.",
  rh_bc23: "(Episode 3) Use your rocket at the edge of one of the support pillars in the water. Release the rocket at the height of your jump.",
  rh_bc24: "(Episode 3) Use your rocket on the network of pillars in the far part of the harbor. Atop one of the higher pillars, you will find an M Graffiti.",
  rh_bc25: "(Episode 3) Use your rocket to get to the cliffs with the palm trees in the far part of the harbor. The second cliff has an M Graffiti.",
  rh_bc26: "(Episode 4) Defeat the Blooper in the cage where you got the Episode 3 Shine.",
  rh_bc27: "(Episode 6) Spray the basket of fish in the fish market.",
  rh_bc28: "(Episode 7) Use the Turbo Nozzle to get Blue Coin #21's counterpart by spraying the X Graffiti and turboing to the tower.",
  rh_bc29: "(Episode 8) Use Yoshi to eat all the blue butterflies near the fish market.",
  rh_bc30: "(Episode 8) Use Yoshi to eat the Yellow Spider on the wall near the tower.",
  // Gelato Beach
  gb_bc1: "(Episode 1) Stomp the only red Cataquack in the center of the beach.",
  gb_bc2: "(Episode 1) Underwater near the palm tree island.",
  gb_bc3: "(Episode 1) Underwater far from land.",
  gb_bc4: "(Episode 1) Use your Squirt Nozzle to propel the swing near the palm tree island.",
  gb_bc5: "(Episode 1) At the tip of the hanging palm on the palm tree island. Walk it very slowly.",
  gb_bc6: "(Episode 1) Swimming with the school of red fish. Swim rapidly after it by lining up your shadows and holding down the A Button while you swim.",
  gb_bc7: "(Episode 1) Swimming with the school of blue fish, found much farther than the red fish.",
  gb_bc8: "(Episode 1) On the ceiling of the Surf Cabana.",
  gb_bc9: "(Episode 1) Swim underneath the Watermelon Shack.",
  gb_bc10: "(Episode 1) Hover up the hillside in the south part of the beach. The coin is behind a rocky crag, at the end of the Ampitheatre path.",
  gb_bc11: "(Episode 1) The triangle graffiti on the north part of the island.",
  gb_bc12: "(Episode 1) The triangle graffiti on the south part of the island.",
  gb_bc13: "(Episode 1) Clean the M Graffiti in the little alcove on the north side of the beach.",
  gb_bc14: "(Episode 1) Hose down one of the Blue Birds in the Ampitheatre.",
  gb_bc15: "(Episode 1) Hose down one of the Blue Birds in the Ampitheatre",
  gb_bc16: "(Episode 1) Jump from wire to wire to get the Blue Coin atop the highest wire in the south part of the island.",
  gb_bc17: "(Episode 1) Atop one of the wire posts to the north.",
  gb_bc18: "(Episode 1) Water the sand to reveal a shine sprite in the south part of the beach.",
  gb_bc19: "(Episode 1) Water the sand in the middle part of the beach.",
  gb_bc20: "(Episode 1) Water the sand in the north part of the beach.",
  gb_bc21: "(Episode 2) Water the sand on the small peninsula, where the sand castle used to be.",
  gb_bc22: "(Episode 4) In the Sand Bird Area, there is a Blue Coin on a cloud.",
  gb_bc23: "(Episode 4) In the Sand Bird Area, there is a Blue Coin on a cloud.",
  gb_bc24: "(Episode 4) In the Sand Bird Area, there is a Blue Coin on a cloud.",
  gb_bc25: "(Episode 4) In the Sand Bird Area, there is a Blue Coin on a cloud.",
  gb_bc26: "(Episode 5) Far above the top of the Giant Hut near the tower. Use the Rocket Nozzle.",
  gb_bc27: "(Episode 5) There is a Blue Cataquack sleeping on a tree by the tower. Defeat him for a Blue Coin.",
  gb_bc28: "(Episode 6) You can take a piece of fruit to the blender on top of the watermelon shack, and drop it into the blades for a Blue Coin.",
  gb_bc29: "(Episode 6) As Yoshi, use juice to melt the Orange Zigzag on the beach and reveal a sprout that contains a Blue Coin.",
  gb_bc30: "(Episode 6) As Yoshi, knock down the beehive under the building by the tower and eat all the bees.",
  // Pinna Park
  pp_bc1: "(Episode 1) Spray the beach to reveal the blue sunshine shape between a basket and palm tree.",
  pp_bc2: "(Episode 1) Spray out another sunshine image by the cannon.",
  pp_bc3: "(Episode 1) Clean the M Graffiti off of the red wall.",
  pp_bc4: "(Episode 1) A Blue Coin is in the pond near the entrance to the park.",
  pp_bc5: "(Episode 1) Spray the X Graffiti near the pond, then run up to the Deku Tree for the the Blue Coin.",
  pp_bc6: "(Episode 1) Spray the X Graffiti on the Deku Tree, then head to the X by the pond.",
  pp_bc7: "(Episode 1) Above one of the swinging pirate ships.",
  pp_bc8: "(Episode 1) Spray the Blue Bird on the awning near the entrance.",
  pp_bc9: "(Episode 1) Spray open the green clam in the clam ride near the entrance.",
  pp_bc10: "(Episode 1) Defeat the stack of Dangos in the back of the park by spraying off the little ones, then jump on the big one.",
  pp_bc11: "(Episode 1) There is a Triangle Graffiti by the Ferris Wheel. Spray it, then drop to the second one on the grassy hill near the pirate ships.",
  pp_bc12: "(Episode 1) Spray the triangle graffiti on the grassy hill, then head to the Ferris Wheel.",
  pp_bc13: "(Episode 1) In the green cage by the pirate ships.",
  pp_bc14: "(Episode 1) Wait until the pirate ship is going fast enough to flip upside down, then jump on the underside of the ship, turn, and jump-hover to the platform above the green cage.",
  pp_bc15: "(Episode 1) Climb up the ramp to the wood platform, then hover into this coin.",
  pp_bc16: "(Episode 1) Hover accross to the platform with the palm tree and broken bridge. The Blue Coin is behind the hill.",
  pp_bc17: "(Episode 1) Spray the Blue Bird on the gondola.",
  pp_bc18: "(Episode 1) Behind the Ferris Wheel, there is an M Graffiti above some brick blocks.",
  pp_bc19: "(Episode 1) Clean the M Graffiti by the palm tree in the small beach.",
  pp_bc20: "(Episode 1) On top of the Ferris Wheel, there are some O Graffitis. Hop onto the ferris wheel from below, then ride it up to the O Graffiti.",
  pp_bc21: "(Episode 1) The O graffiti counterpart on the opposite side of the Ferris Wheel.",
  pp_bc22: "(Episode 2) In a basket on the beach. Use the purple homing Bullet Bills to break the basket.",
  pp_bc23: "(Episode 2) In a basket on the beach. Use the purple homing Bullet Bills to break the basket.",
  pp_bc24: "(Episode 2) In a basket on the beach. Use the purple homing Bullet Bills to break the basket.",
  pp_bc25: "(Episode 2) In a basket on the beach. Use the purple homing Bullet Bills to break the basket.",
  pp_bc26: "(Episode 2) In a basket on the beach. Use the purple homing Bullet Bills to break the basket.",
  pp_bc27: "(Episode 2) In a basket on the beach. Use the purple homing Bullet Bills to break the basket.",
  pp_bc28: "(Episode 5) Use Yoshi to eat the Blue Butterfly outside the Park.",
  pp_bc29: "(Episode 5) Use Yoshi to eat the other Blue Butterfly outside the Park.",
  pp_bc30: "(Episode 6) Use Yoshi to eat the Blue Butterfly on the small beach near the fountain inside the park.",
  // Sirena Beach
  sb_bc1: "(Episode 1) In the water at the edge of the cliffs north of the starting point.",
  sb_bc2: "(Episode 1) Help the Noki stuck in the sludge. Talk to him for a Blue Coin.",
  sb_bc3: "(Episode 1) Help the other Noki stuck in the sludge. Talk to her for a Blue Coin.",
  sb_bc4: "(Episode 2) Spray the tablet by the lounge chairs.",
  sb_bc5: "(Episode 2) Spray the flower bed to the right of the hotel, by the three barrels.",
  sb_bc6: "(Episode 2) Put out the second flame from the left in front of the hotel.",
  sb_bc7: "(Episode 2) In the ceiling of the little hut on the right.",
  sb_bc8: "(Episode 2) Hover from the top of a hut, to the second level of the hotel. The Blue Coin is in the back.",
  sb_bc9: "(Episode 2) Spray the Lamp on the third floor inside the hotel.",
  sb_bc10: "(Episode 3) Spray the bookcase on the left in the third floor of the hotel when on your Pineapple hunt.",
  sb_bc11: "(Episode 3) Shoot the Dolphin Poster on the third floor to open up a room with the Blue Coin.",
  sb_bc12: "(Episode 3) Have Yoshi eat the giant boo in the Pineapple Room.",
  sb_bc13: "(Episode 3) In the maze on the 4th floor.",
  sb_bc14: "(Episode 3) In the hotel room with a single pineapple, spray the blank picture. This room can be accessed from a tile in the maze on the 4th floor.",
  sb_bc15: "(Episode 3) In the hotel room with a single pineapple, Ground Pound the glass table. This room can be accessed from a tile in the maze on the 4th floor.",
  sb_bc16: "(Episode 3) Spray the giant skylight above the totem pole on the third floor.",
  sb_bc17: "(Episode 4) Destroy the Boo in the maze on the 4th Floor for a Blue Coin.",
  sb_bc18: "(Episode 4) In the crate room where you got the Pineapple in the previous Episode, Ground Pound a crate for the Blue Coin. This room can be accessed by going to the 4th Floor Maze, Ground Pound the tile that leads to the Dolphic Poster Room, then ground pounding the tile that leads to the crate room.",
  sb_bc19: "(Episode 4) In the Casino, ground pound the slot machines to the left of the entrance.",
  sb_bc20: "(Episode 4) In the Casino, put out the flame in the fountain to the right of the entrance.",
  sb_bc21: "(Episode 5) In the Casino, clean the M Graffiti above the entrance door.",
  sb_bc22: "(Episode 6) Help the Noki by the lounge chairs and talk to him.",
  sb_bc23: "(Episode 6) Help the Noki by the lounge chairs and talk to her.",
  sb_bc24: "(Episode 7) Clean off the M Graffiti to the right of the Hotel.",
  sb_bc25: "(Episode 7) Shoot the Triangle Graffiti in the lobby, then Wall Kick and hover up the totem pole to get to the other one.",
  sb_bc26: "(Episode 7) Shoot the Triangle Graffiti on the floor above the lobby then jump down the totem pole to get the lobby.",
  sb_bc27: "(Episode 7) Spray the X Graffiti on the second floor, then dash up the stairs to the third floor.",
  sb_bc28: "(Episode 7) Spray the X Graffiti on the third floor, then dash down the stairs to the second floor.",
  sb_bc29: "(Episode 7) Clean the M Graffiti on the third floor.",
  sb_bc30: "(Episode 7) Clean the M Graffiti in the maze on the 4th floor.",
  // Noki Bay
  nb_bc1: "(Episode 1) Just above the surface of the water. You can hover to it from the shell spire or take the boat.",
  nb_bc2: "(Episode 1) Above the water, near the coast. Take the boat to it or hover up to it from the water.",
  nb_bc3: "(Episode 1) Deep under water below the racoon's hut, down the path of coins.",
  nb_bc4: "(Episode 1) Hover-Jump down from the cliff with the tree and the gold bird, and to your left, and you will find an M Graffiti.",
  nb_bc5: "(Episode 1) Hover-Jump down from the cliff with the tree and the gold bird, to the platform with seven panels. Spray the lower-left panel to open an alcove with a Blue Coin.",
  nb_bc6: "(Episode 1) In the same area as Blue Coin #5, spray the upper-right panel.",
  nb_bc7: "(Episode 1) Drop from the area with the seven panels, to your left, and you will find a Blue Coin in the alcove.",
  nb_bc8: "(Episode 1) Drop from above, where the seven panels are, onto a ledge to the right. From there, you can easily hover to the Blue Coin visible in the alcove.",
  nb_bc9: "(Episode 1) Rocket into the Blue Coin above the empty alcove shown in the picture.",
  nb_bc10: "(Episode 1) Spray the panel above the rift in the west cliff (which you must fall to from above or rocket up to), and wall kick up to various paths. The lowest path leads to a part with two panels, the higher of which contains a Blue Coin.",
  nb_bc11: "(Episode 1) Standing in front of the west cliff, rocket up (or fall down from the tree area) to the lowest ledge on the left and spray open the two hidden alcoves. The Blue Coin is at the top.",
  nb_bc12: "(Episode 1) In a secret alcove (which must be sprayed open) right above the Blue Coin #11 alcove and slightly to the left.",
  nb_bc13: "(Episode 1) Another secret alcove like 11 and 12. Fall and hover from the tree to a ledge on the far left side of the cliff.",
  nb_bc14: "(Episode 1) Get the rocket nozzle on the far right side of the cliff, and rocket up to the coin trail above the rocket nozzle ledge.",
  nb_bc15: "(Episode 1) Get a Blue Coin from the alcove just above the one where you found the rocket nozzle.",
  nb_bc16: "(Episode 1) Hover across to an alcove toward the center of the cliff from the ledge with the little pond on the way up to the Episode 1 boss.",
  nb_bc17: "(Episode 1) Jump the verticle shaft in the center of the cliff, directly below the alcove where you found Blue Coin #16.",
  nb_bc18: "(Episode 1) Hover across from the purple conch shell atop the seashell spire to the Blue Coin in the left (west) cliff.",
  nb_bc19: "(Episode 1) Stand on the thin ledge between the top water wheel and the cliff, and spray the cliff at the far end of the inner rim. Hover over to the secret alcove.",
  nb_bc20: "(Episode 1) From the thin ledge described above, spray in the corner of the cliffs along the lower rim.",
  nb_bc21: "(Episode 2) Spray the wall panel above the old Noki, and jump into the weird structure it creates. In the middle is a Blue Coin.",
  nb_bc22: "(Episode 2) In the second wall panel structure, in one of the small alcoves near the top.",
  nb_bc23: "(Episode 2) Spray one of the vases in the Noki Tomb where the Shine is in Episode 2.",
  nb_bc24: "(Episode 2) Spray another vase in the Noki Tomb where the Shine is in Episode 2.",
  nb_bc25: "(Episode 4) In the underwater area in Episodes 4 and 8, atop one of the highest pillars.",
  nb_bc26: "(Episode 4) In the underwater area in Episodes 4 and 8, atop one of the highest pillars.",
  nb_bc27: "(Episode 4) In the underwater area in Episodes 4 and 8, atop one of the middle-level pillars.",
  nb_bc28: "(Episode 4) In the underwater area in Episodes 4 and 8, atop one of the middle-level pillars.",
  nb_bc29: "(Episode 6) Spray the graffiti near the boathouse it from atop the boathouse, Jump-Dive off, then Hover-Swim across (or spray it from the boat and sail across).",
  nb_bc30: "(Episode 6) The counterpart to the graffiti near the boathouse, spray it from one of the seashells on the spire, Jump-Dive toward the boathouse, then hover-swim across.",
  // Pianta Village
  pv_bc1: "(Episode 1) Clean off the M graffiti on the wall directly behind this level's starting point.",
  pv_bc2: "(Episode 1) Jump off the bridge and hover onto the catwalk, or ground pound onto it from one of the revolving gates in town. Clean the M Graffiti on the ceiling.",
  pv_bc3: "(Episode 1) Just past the bridge, you will see a green building to your right. Clean off the M Graffiti.",
  pv_bc4: "(Episode 1) In the far left corner of the village, you will see an M graffiti near an arch.",
  pv_bc5: "(Episode 1) Spin jump onto the yellow mushroom atop the highest platform in town. Aim at the moon with your squirt nozzle, and spray it.",
  pv_bc6: "(Episode 1) Climb the mushroom-studded tree just to your left as you cross the bridge. When you get to the top, turn and climb the palm frond to your left. You will see the Blue Coin on a ledge to Mario's right.",
  pv_bc7: "(Episode 1) A Blue Coin is lying in the thick grass just past the mushroom tree to the left of the bridge, between the palm tree and the swing.",
  pv_bc8: "(Episode 1) Ground pound the nose of the Pianta Statue in the far side of town.",
  pv_bc9: "(Episode 1) Climb the giant palm tree to the left of the statue. The Blue Coin is waiting in the center of the treetop.",
  pv_bc10: "(Episode 1) In the pool area, squirt at the hole that is the source of the fountain.",
  pv_bc11: "(Episode 1) Follow the stream from the pool to where it drops off the edge, and you will find a Blue Coin in the water at the end.",
  pv_bc12: "(Episode 1) Follow the stream back up to the pool, and you will find a Blue Coin under a small natural bridge.",
  pv_bc13: "(Episode 1) Cool off the Chain Chomplets so they won't get in the way, then shoot the first Triangle Graffiti, and Hover-Jump across to the second, near the swing in the rear of the village.",
  pv_bc14: "(Episode 1) The counterpart to Blue Coin #13, near the Chain Chomplet's path. Clean the molten muck first, spray the Graffiti, and water slide down the path, then hover over the bath area.",
  pv_bc15: "(Episode 2) Spray the sign to your right immediately after you cross the bridge from your starting point.",
  pv_bc16: "(Episode 3) Clean the M Graffiti on the platform where you retrieve FLUDD.",
  pv_bc17: "(Episode 3) Squirt through the much to find a giant M Graffiti between the two mushrooms near the bridge, to the left from start.",
  pv_bc18: "(Episode 3) Find the flaming Pianta at the right side of the village and extinguish the flames for a Blue Coin.",
  pv_bc19: "(Episode 5) Knock down the beehive with Yoshi right across the bridge and to your right. Have Yoshi eat all the bees for a Blue Coin.",
  pv_bc20: "(Episode 5) Spin onto the top of the fruit tree, and then to the mushroom nearby. Have Yoshi eat all of the blue butterflies for a Blue Coin.",
  pv_bc21: "(Episode 5) On the tree to the left of the bath area in the very back, knock off the hive and have Yoshi eat all the bees.",
  pv_bc22: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc23: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc24: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc25: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc26: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc27: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc28: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc29: "(Episode 6) Receive a Blue Coin from a Pianta trapped under the sludge.",
  pv_bc30: "(Episode 8) From atop the large central tree, spray the Blue Bird three times.",
};